# ===================================================================
# CONFIGURATION DE LA BASE DE DONNÉES (POSTGRESQL)
# ===================================================================

# URL pointant sur ta base locale nommée dans DBeaver
spring.datasource.url=jdbc:postgresql://localhost:5432/cursur_db
spring.datasource.username=postgres

# /!\ METS ICI TON VRAI MOT DE PASSE POSTGRES (CELUI UTILISÉ SUR DBEAVER) /!\
spring.datasource.password=admin123

spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURATION HIBERNATE / JPA
# ===================================================================

# Permet à Spring Boot de créer/mettre à jour automatiquement tes tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Affiche les requêtes SQL dans la console (pratique pour débugger)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
