spring.application.name=cursus-api
# ==========================================
# CONFIGURATION DE LA BASE DE DONNÉES MYSQL
# ==========================================

# URL de connexion : on se connecte sur localhost (port 3306) à la base "cursus_universitaire"
spring.datasource.url=jdbc:mysql://localhost:3306/cursus_universitaire?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# Identifiants MySQL (Mets tes propres identifiants si différents)
spring.datasource.username=root
spring.datasource.password=

# Spécification du pilote JDBC pour MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# CONFIGURATION JPA / HIBERNATE
# ==========================================

# 'update' : Hibernate va créer ou modifier automatiquement les tables SQL par rapport à nos classes Java
spring.jpa.hibernate.ddl-auto=update

# Affiche les requêtes SQL générées par Spring dans la console (très utile pour débugger)
spring.jpa.show-sql=true

# Formate proprement le SQL affiché dans la console pour qu'il soit lisible
spring.jpa.properties.hibernate.format_sql=true

# Indique à Hibernate qu'on utilise le langage SQL spécifique à MySQL
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Port sur lequel ton API va tourner (par défaut 8080)
server.port=8080