# Configuration de la base de données dynamique
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cursus_universitaire}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${PORT:8080}

# Gestion des tables (création automatique si elles n'existent pas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true